config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'
  get 'dashboard', to: 'home#dashboard'
  resources :group, :only => [:new, :create, :show, :edit, :destroy] do
    resources :payment, :only => [:new, :create, :show, :edit, :destroy] do
      collection do
        get :history
      end
    end
    collection do
      get :list
      get :join
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :transactions
  accepts_nested_attributes_for :transactions, allow_destroy: true
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  before_action :authenticate_user!

  def new
    @payment = Payment.new
    @payment.transactions.build
    @group = Group.find(params[:group_id])
    @group_users = @group.group_users
  end

  def create
    @payment = Payment.new(payment_params)
    #@payment.transactions.build


  end

  def history

  end

  private
  def payment_params
    params.require(:payment).permit(
      :user_id, :group_id, :from, :to, :amount, :description, :resolved, :deleted,
      transactions_attributes: [:id, :payment_id, :from_id, :to_id, :resolved, :deleted, :ids]
    )
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payment/history.html.slim
.row
  h6.col.s12 支払履歴
  ul.collection

app/views/payment/new.html.slim
.row
  = form_for @payment, url: group_payment_index_path do |f|
    .row
      h6.col.s12  支払内容を入力してください
      .input-field.col.s12
        = f.text_field :description, placeholder: "（例）昼食代"
        label for="description" 支払内容
      .input-field.col.s12
        = f.text_field :amount, placeholder: "1800"
        label for="amount" 支払金額
      .input-field.col.s12
        = f.select :user_id, options_for_select(@group_users.pluck(:user_id).map{|u| [User.find(u).name, u]}), selected: current_user.id
        label 支払ユーザー

      = f.fields_for :transaction do |g|
        h6.col.s12 精算対象者を選択してください

        .col.s12
          - @group_users.each do |group_user|
            p
              = g.check_box :to_ids, { multiple: true, checked: group_user[:checked], include_hidden: false, class: "filled-in" }, group_user.user_id, nil
              label for="payment_transaction_to_ids_#{group_user.user_id}" #{group_user.user.name}
      .input-field.col.s12.center
        = f.submit '登録する', class: 'waves-effect waves-light btn center'