config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'
  get 'dashboard', to: 'home#dashboard'
  resources :group, :only => [:new, :create, :show, :edit, :destroy] do
    resources :payment, :only => [:new, :create, :show, :edit, :destroy] do
      collection do
        get :history
      end
    end
    collection do
      get :list
      get :join
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  # ログイン前トップ
  def index
    if user_signed_in?
      redirect_to :dashboard
    end

  end

  # ダッシュボード
  def dashboard
     @group_users = current_user.group_users
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.slim
.row
  h5.col.s12.center = current_user.name

.row
  .col.s12
  ul.collection
    - @group_users.each do |group_user|
      = link_to "#{group_user.group.name}", group_user.group, :class => 'collection-item'

.row
  .col.s12
    = link_to "グループリスト", list_group_index_path
  .col.s12
    = link_to "グループ作成", new_group_path
  .col.s12
    = link_to 'サインアウト', destroy_user_session_path, method: :delete

app/views/home/index.html.slim
.row
  .col.s12.center
    =  link_to image_tag('flogo.svg', {:width => '200', :border => 0, :alt => 'Facebookでログイン'}), user_facebook_omniauth_authorize_path

  .col.s12.center
    = link_to 'サインアウト', destroy_user_session_path, method: :delete