config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'
  get 'dashboard', to: 'home#dashboard'
  resources :group, :only => [:new, :create, :show, :edit, :destroy] do
    resources :payment, :only => [:new, :create, :show, :edit, :destroy] do
      collection do
        get :history
      end
    end
    collection do
      get :list
      get :join
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!


  # 新規グループ作成画面
  def new
    @group = Group.new
  end

  # 新規グループ作成ロジック・作成完了画面
  def create
    require 'securerandom'
    @group = Group.new(group_params)
    @group.code = SecureRandom.hex(8)

    if @group.save
      @group_user = GroupUser.new
      @group_user.user_id = current_user.id
      @group_user.group_id = @group.id
      @group_user.role = 'owner'
      @group_user.save

      redirect_to @group, notice: 'グループを作成しました'
    else
      render :new, notice: 'グループを作成できませんでした'
    end
    
  end

  # グループ詳細画面
  def show
    @group = Group.find(params[:id])
    @group_users = @group.group_users
  end

  # 所属グループ一覧画面
  def list
    @group_users = current_user.group_users

  end

  # グループ編集画面
  def edit

  end

  # グループ削除画面
  def destroy

  end

  # グループ参加画面
  def join
    code = params[:code]
    @group = Group.find_by_code(code)

  end

  private
  def group_params
    params.require(:group).permit(:name, :code)
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/join.html.slim
.row
  h5.col.s12.center = @group.name

app/views/group/list.html.slim
.row
  h6.col.s12 グループリスト
  ul.collection
    - @group_users.each do |group_user|
      = link_to "#{group_user.group.name}", group_user.group, :class => 'collection-item'

app/views/group/new.html.slim
.row
  = form_for @group, url: group_index_path do |f|
    h6.col.s12 新しくグループを作成します
    .input-field.col.s12
      = f.text_field :name
      label for="name" グループ名
    .input-field.col.s12.center
      = f.submit '作成する', class: 'waves-effect waves-light btn center'

app/views/group/show.html.slim
.row
  h5.col.s12.center = @group.name
  span.col.s12.center = "招待コード：#{@group.code}"

.row
  ul.collection
    = link_to "支払登録", new_group_payment_path(group_id: params[:id]), :class => 'collection-item'
    = link_to "支払履歴", history_group_payment_index_path(group_id: params[:id]), :class => 'collection-item'


.row
  h6.col.s12 メンバーリスト
  ul.collection
    - @group_users.each do |group_user|
      = link_to root_path, {:class => 'collection-item'} do
        = group_user.user.name
        span.badge.new.red data-badge-caption="円" -50,000